version: '3.4'
services:
  osticket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=osticket
    # depends_on:
    #   - mysql

  # mysql:
  #   image: mysql:5.7
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=your_mysql_root_password
  #     - MYSQL_DATABASE=osticket
  #     - MYSQL_USER=osticket
  #     - MYSQL_PASSWORD=osticket
