version: '3.4'
services:
  osticket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=osticket
      - DB_USER=osticket
      - DB_PASSWORD=osticket
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_root_password
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=osticket
